project_id = "ivxfajtibkqytrvvvirb"

[functions.ai-intelligence-processor]
verify_jwt = false

[functions.zuhu-content-classifier]
verify_jwt = false

[functions.zuhu-design-director]
verify_jwt = false

[functions.zuhu-asset-manager]
verify_jwt = false

[functions.zuhu-page-composer]
verify_jwt = false

[functions.zuhu-seo-synthesizer]
verify_jwt = false

[functions.zuhu-unified-processor]
verify_jwt = false

[functions.quality-fortress]
verify_jwt = false

[functions.autonomous-publishing-engine]
verify_jwt = false