project_id = "ivxfajtibkqytrvvvirb"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "IPv4"
max_header_length = 4096

[studio]
enabled = true
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"
port = 54323

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000", "http://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false
# Development settings for easier testing
enable_manual_linking = true

[functions.ai-intelligence-processor]
verify_jwt = false

[functions.mcp-converter]
verify_jwt = false

[functions.zuhu-asset-manager]
verify_jwt = false

[functions.zuhu-content-classifier]
verify_jwt = false

[functions.zuhu-design-director]
verify_jwt = false

[functions.zuhu-page-composer]
verify_jwt = false

[functions.zuhu-seo-synthesizer]
verify_jwt = false

[functions.zuhu-unified-processor]
verify_jwt = false

[functions.quality-fortress]
verify_jwt = false

[functions.autonomous-publishing-engine]
verify_jwt = false

[functions.zuhu-pipeline-validator]
verify_jwt = false

[functions.ai-coder-agent]
verify_jwt = false

[functions.shaper-ai]
verify_jwt = false

[functions.github-publisher]
verify_jwt = false

# Storage configuration for development
[storage]
enabled = true
file_size_limit = "50MiB"
image_transformation = { enabled = true }

# Email testing with Inbucket
[inbucket]
enabled = true
port = 54324
smtp_port = 2500

# Edge Runtime for Functions
[edge_runtime]
enabled = true
inspector_port = 8083
policy = "per_worker"
