# Netlify Configuration - Optimized for Reliability
[build]
  base = "/"
  command = "npm run build"
  publish = "dist/"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Force production branch to main
[context.production]
  command = "npm run build"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200