// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdrothbhxifntjwhzogt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impkcm90aGJoeGlmbnRqd2h6b2d0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMjc4MDEsImV4cCI6MjA3MDYwMzgwMX0.qeNbk0fnVoHYkQ8-P6Cu9c5BNmQ2FQiszBXHW1fxIyM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});